### ISSUE TITLE
delete survey functionality not working 

### ISSUE THREAD

**Issue by vanillacandy** [surveyjs/surveyjs-nodejs#10]
### Are you requesting a feature, reporting a bug or asking a question?
asking a question

### What is the current behavior?
when I delete the survey, it popped out a box asking if I am sure to delete, I hit yes, then the survey didn't get deleted. 

### What is the expected behavior?
Survey should be deleted after the delete button is clicked. 

### How would you reproduce the current behavior (if this is a bug)?
By clicking on the delete button

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser: firefox
* browser version: Version 	68.1.0esr
* surveyjs platform (angular or react or jquery or knockout or vue): I only did git clone and npm start
* surveyjs version:surveyjs-nodejs@0.1.0

**Comment by tsv2013** [comment]
Am I right and this question is related to `surveyjs-nodejs` repo? This repo demonstrates how to integrate SurveyJS client-side libraries with NodeJS backend. It doesn't have aim to demonstrate how to work with any database. That's why some functionality was ommited in favour of simplicity. 

More over if anyone can delete demo data then others can't see anything ;-)

**Comment by tsv2013** [comment]
Remove wasn't processed on client. Fixed via the https://github.com/surveyjs/surveyjs-nodejs/commit/08a4d51795767a4b9ec0a2eac238d62d55e37166 commit
